version: '3'

services: 
  eureka:
    build: ./service/service_registry
    image: sumrid/soa_eureka
    ports: 
      - 8761:8761

  api-gateway: 
    build: ./service/apigateway
    image: sumrid/soa_apigateway
    ports: 
      - 8085:8080
    depends_on: 
      - eureka

  product-service:
    build: ./product_service
    image: sumrid/soa_product
    ports: 
      - 8080:8080
    restart: always
    depends_on: 
      - eureka
  
  bill-service:
    build: ./bill_service
    image: sumrid/soa_bill
    ports: 
      - 8081:8080
    restart: always
    depends_on: 
      - eureka

  report-service:
    build: ./report_service
    image: sumrid/soa_report
    ports: 
      - 8082:8080
    restart: always
    depends_on: 
      - eureka

  stock-service:
    build: ./stock_service
    image: sumrid/soa_stock
    ports: 
      - 8083:8080
    restart: always
    depends_on: 
      - eureka

  user-service:
    build: ./user_service
    image: sumrid/soa_user
    ports: 
      - 8084:5000
    restart: always
    depends_on: 
      - eureka

  ########## Web #########
  web:
    build: ./web
    image: sumrid/soa_web
    ports: 
      - 80:3000
    depends_on: 
      - product-service
      - bill-service
      - report-service
      - stock-service
      - user-service