version: 2
jobs:
  build-bill:
    working_directory: ~/soa2019_group7/bill_service/
    docker:
      - image: google/cloud-sdk
    steps:
      - checkout:
          path: ~/soa2019_group7
      - setup_remote_docker:
          docker_layer_caching: true
      - run:
          name: chmod permissions
          command: chmod +x ./gradlew
      - run :
          name: Auth to gcloud
          command: |
            echo $GCLOUD_KEY | gcloud auth activate-service-account --key-file=-
            gcloud --quiet config set project ${PROJECT_ID}
            gcloud container clusters get-credentials soa-service --zone asia-southeast1-b --project soa-group-7-174
            gcloud auth configure-docker
      - run :
          name: Build and push docker images
          command: |
            ./gradlew clean build
            docker build -t asia.gcr.io/soa-group-7-174/bill:$CIRCLE_BUILD_NUM .
            docker push asia.gcr.io/soa-group-7-174/bill:$CIRCLE_BUILD_NUM
            kubectl set image deployment/bill bill=asia.gcr.io/soa-group-7-174/bill:$CIRCLE_BUILD_NUM

  build-report:
    working_directory: ~/soa2019_group7/report_service
    docker:
      - image: google/cloud-sdk
    steps:
      - checkout:
          path: ~/soa2019_group7
      - setup_remote_docker:
          docker_layer_caching: true
      - run:
          name: chmod permissions
          command: chmod +x ./gradlew
      - run :
          name: Auth to gcloud
          command: |
            echo $GCLOUD_KEY | gcloud auth activate-service-account --key-file=-
            gcloud --quiet config set project ${PROJECT_ID}
            gcloud container clusters get-credentials soa-service --zone asia-southeast1-b --project soa-group-7-174
            gcloud auth configure-docker
      - run :
          name: Build and push docker images
          command: |
            ./gradlew clean build
            # docker build -t asia.gcr.io/soa-group-7-174/report:$CIRCLE_BUILD_NUM .
            # docker push asia.gcr.io/soa-group-7-174/report:$CIRCLE_BUILD_NUM
            # kubectl set image deployment/report report=asia.gcr.io/soa-group-7-174/report:$CIRCLE_BUILD_NUM

  user-service:
      working_directory: ~/soa2019_group7/user_service
      docker:
        - image: google/cloud-sdk
      steps:
        - checkout:
            path: ~/soa2019_group7
        - setup_remote_docker:
            docker_layer_caching: true
        - run:
            name: chmod permissions
            command: chmod +x ./gradlew
        - run :
            name: Auth to gcloud
            command: |
              echo $GCLOUD_KEY | gcloud auth activate-service-account --key-file=-
              gcloud --quiet config set project ${PROJECT_ID}
              gcloud container clusters get-credentials soa-service --zone asia-southeast1-b --project soa-group-7-174
              gcloud auth configure-docker
        - run :
            name: Build and push docker images
            command: |
              ./gradlew clean build
              docker build -t asia.gcr.io/soa-group-7-174/user:$CIRCLE_BUILD_NUM .
              docker push asia.gcr.io/soa-group-7-174/user:$CIRCLE_BUILD_NUM
              kubectl set image deployment/user user=asia.gcr.io/soa-group-7-174/user:$CIRCLE_BUILD_NUM

  build-product:
    working_directory: ~/soa2019_group7/product_service
    docker:
      - image: google/cloud-sdk
    steps:
      - checkout:
          path: ~/soa2019_group7
      - setup_remote_docker:
          docker_layer_caching: true
      - run:
          name: chmod permissions
          command: chmod +x ./mvnw
      - run :
          name: Auth to gcloud
          command: |
            echo $GCLOUD_KEY | gcloud auth activate-service-account --key-file=-
            gcloud --quiet config set project ${PROJECT_ID}
            gcloud container clusters get-credentials soa-service --zone asia-southeast1-b --project soa-group-7-174
            gcloud auth configure-docker
      - run :
          name: Build and push docker images
          command: |
            docker build -t asia.gcr.io/soa-group-7-174/product:$CIRCLE_BUILD_NUM .
            docker push asia.gcr.io/soa-group-7-174/product:$CIRCLE_BUILD_NUM
            kubectl set image deployment/product product=asia.gcr.io/soa-group-7-174/product:$CIRCLE_BUILD_NUM

  build-stock:
    working_directory: ~/soa2019_group7/stock_service
    docker:
      - image: google/cloud-sdk
    steps:
      - checkout:
          path: ~/soa2019_group7
      - setup_remote_docker:
          docker_layer_caching: true
      - run:
          name: chmod permissions
          command: chmod +x ./mvnw
      - run :
          name: Auth to gcloud
          command: |
            echo $GCLOUD_KEY | gcloud auth activate-service-account --key-file=-
            gcloud --quiet config set project ${PROJECT_ID}
            gcloud container clusters get-credentials soa-service --zone asia-southeast1-b --project soa-group-7-174
            gcloud auth configure-docker
      - run :
          name: Build and push docker images
          command: |
            docker build -t asia.gcr.io/soa-group-7-174/stock:$CIRCLE_BUILD_NUM .
            docker push asia.gcr.io/soa-group-7-174/stock:$CIRCLE_BUILD_NUM
            kubectl set image deployment/stock stock=asia.gcr.io/soa-group-7-174/stock:$CIRCLE_BUILD_NUM

  build-web:
    working_directory: ~/soa2019_group7/web
    docker:
      - image: circleci/node:10
    steps:
      - checkout:
          path: ~/soa2019_group7
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            - v1-dependencies-
      - run:
          name: build web
          command: 
            npm install
            yarn build
      - store_test_results:
          path: test-results

  deploy-web:
    working_directory: ~/soa2019_group7/web
    docker:
      - image: google/cloud-sdk
    steps:
      - checkout:
          path: ~/soa2019_group7
      - setup_remote_docker:
          docker_layer_caching: true
      - run :
          name: Auth to gcloud
          command: |
            echo $GCLOUD_KEY | gcloud auth activate-service-account --key-file=-
            gcloud --quiet config set project ${PROJECT_ID}
            gcloud container clusters get-credentials soa-service --zone asia-southeast1-b --project soa-group-7-174
            gcloud auth configure-docker
      - run :
          name: Build and push docker images
          command: |
            docker build -t asia.gcr.io/soa-group-7-174/web:$CIRCLE_BUILD_NUM .
            docker push asia.gcr.io/soa-group-7-174/web:$CIRCLE_BUILD_NUM
            # kubectl set image deployment/web web=asia.gcr.io/soa-group-7-174/web:$CIRCLE_BUILD_NUM


workflows:
  version: 2
  workflow:
    jobs:
      # - user-service
      - build-bill
      # - build-report
      # - build-product
      # - build-stock
      # - build-web
      # - deploy-web:
      #     requires:
      #       - build-web

